// <auto-generated />
namespace Photo_album.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class WithForeignKeysMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(WithForeignKeysMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "202108052143012_WithForeignKeysMigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
